# Generated by Django 3.1.4 on 2021-01-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('lefttop_x', models.IntegerField(blank=True, null=True)),
                ('lefttop_y', models.IntegerField(blank=True, null=True)),
                ('rightbottom_x', models.IntegerField(blank=True, null=True)),
                ('rightbottom_y', models.IntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
                ('box_id', models.CharField(blank=True, max_length=10, null=True)),
                ('truncated', models.CharField(blank=True, max_length=1, null=True)),
                ('hidden', models.CharField(blank=True, max_length=1, null=True)),
                ('light_reflex', models.CharField(blank=True, max_length=1, null=True)),
                ('na', models.CharField(blank=True, max_length=1, null=True)),
                ('flag', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'annotations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('supercategory', models.CharField(blank=True, max_length=10, null=True)),
                ('metainfo', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('license_id', models.IntegerField()),
                ('file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('image_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('possession', models.CharField(max_length=20)),
                ('license_id', models.IntegerField()),
            ],
            options={
                'db_table': 'licenses',
                'managed': False,
            },
        ),
    ]
